name: Git Diff Test
on:
  push:
    branches:
      - jonathann/*

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git diff
        run: |
          git branch
          # git log
          # Get file names (excluding deleted files)
          git diff origin/${{ github.event.repository.default_branch }}...HEAD --name-only --diff-filter=ACMRTUXB ./prometheus/alerts/**/*.yml
