name: Git Diff Test
on:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git diff
        run: |
          git branch
          echo "GITHUB_REF: $GITHUB_REF"
          # Get file names (excluding deleted files)
          git diff origin/${{ github.event.repository.default_branch }}...HEAD --name-only --diff-filter=ACMR ./prometheus/alerts/**/*.yml
          echo ">>> PULL_REQUEST_TARGET_REPO: ${PULL_REQUEST_TARGET_REPO}"
          echo ">>> PULL_REQUEST_SOURCE_REPO: ${PULL_REQUEST_SOURCE_REPO}"

      - name: Pint stuff
        run: |
          git branch
          echo "GITHUB_REF: $GITHUB_REF"
          # must set these values for the git pull to work
          git config --global user.email "pint@fakemail.com"
          git config --global user.name "pint"
          git config pull.rebase false
          echo ">>> BASE BRANCH: ${{ github.event.repository.default_branch }}"
          echo ">>> GITHUB HEAD REF: ${GITHUB_HEAD_REF}"
